assets:
  scripts:
    optional:
      posthog:
        key: phc_uCbhFRCieH9tPYbmlaLPtW6pZaEgnOfGENNgcC1KdlA
        host: https://localization.heimlicher.com
        site: heimlicher.com
        environments: prod
        # Set to 'always' to create profiles for anonymous users as well
        # person_profiles: identified_only
        person_profiles: always

# Only enable indexing for production
robots:
  index: true
  indeximages: true
  follow: true
