# https://github.com/gohugoio/hugoDocs/blob/master/config/_default/config.toml
title: Simon Heimlicher
# baseURL: https://simon.heimlicher.com/
baseURL: /

defaultContentLanguage: en
languageCode: en-us

enableRobotsTXT: true
disableAliases: true

build:
  # Write statistics to enable post-processing of CSS
  writeStats: true

timeout: 300s

ignoreFiles:
  - \.DS_Store$
  - \.vscode$
  - .*\.code-workspace$
  - frontmatter\.json$

disableKinds:
  - RSS
  # - taxonomy
  # - term
  # - page
  # - section
  # - RSS
  # - sitemap
  # - robotsTXT
  # - 404

pagination.pagerSize: 20

outputs:
  home:
    - HTML
    - redir
    # - redir_canonical
    # - redir_nginx
    # - redir_canonical_nginx
  page:
    - HTML
  section:
    - HTML
mediaTypes:
  text/redirects:
    delimiter: ""
  # text/nginx:
  #   delimiter: ""
  text/urls:
    delimiter: ""
  text/aliases:
    delimiter: ""
outputFormats:
  redir:
    mediatype: text/redirects
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  redir_canonical:
    mediatype: text/redirects
    baseName: _redirects_canonical
    isPlainText: true
    notAlternative: true
  # redir_nginx:
  #   mediatype: text/nginx
  #   baseName: _redirects.nginx
  #   isPlainText: true
  #   notAlternative: true
  # redir_canonical_nginx:
  #   mediatype: text/nginx
  #   baseName: _redirects_canonical.nginx
  #   isPlainText: true
  #   notAlternative: true
  urls:
    mediatype: text/urls
    baseName: _urls
    isPlainText: true
    notAlternative: true
  aliases:
    mediatype: text/aliases
    baseName: _aliases
    isPlainText: true
    notAlternative: true

markup:
  _merge: deep

# Merge imaging options from theme
imaging:
  _merge: deep

# Merge security from theme, e.g., for asset pipeline
security:
  _merge: deep

# Merge minify from theme, e.g., for asset pipeline
minify:
  _merge: deep

# NOTE: If using excludeFiles, these files are also not available for .Resources.Get
module:
  imports:
    - path: github.com/simonheimlicher/hugo-claris
    # - path: github.com/simonheimlicher/hugo-fontawesome

  mounts:
    - source: assets
      target: assets
      excludeFiles:
        - .DS_Store
    - source: data
      target: data
      excludeFiles:
        - .DS_Store
    - source: static
      target: static
      excludeFiles:
        - .DS_Store
    - source: i18n
      target: i18n
      excludeFiles:
        - .DS_Store
    - source: content
      target: content
      excludeFiles:
        - "**/.DS_Store"
    # "**/*.yaml" # Don't exclude YAML files as they won't be available
    # as Page Bundle resources via resources.Get

permalinks:
  articles: :sections/:filename
taxonomies:
  category: categories
  tag: tags
  series: series
related:
  includeNewer: true
  threshold: 50
  toLower: true
  indices:
    - name: categories
      weight: 100
    - name: tags
      weight: 100
    - name: keywords
      weight: 100
    - name: date
      weight: 10
