canonicalBaseURL: https://simon.heimlicher.com/

siteAuthor: Simon Heimlicher
authors:
  simon-heimlicher:
    last_name: Heimlicher
    first_name: Simon
    email: AUTHOR_EMAIL
    name: Simon Heimlicher
    profilepage: about

mainSections:
  - articles
  - leadership
  - transformation
  - digitization
  - research
  - technology

masthead:
  # The masthead contains a link
  # Default: "/" in the current language
  # If you would like to link to a different page, provide the path of this page below.
  # For example: if you would like the logo to link to `/post`, you would use:
  # linkpath: /post
  logo:
    position: left
    src: site-meta/sh.com-logo.svg
  wordmark: Simon Heimlicher

responsive:
  breakpoints:
    width:
      # From this width upward, the mobile menu is hidden
      # and the full menu bar is shown
      mobile_menu: 60rem
      # From this width upward, font size is set to regular size
      narrow: 32rem

assets:
  styles:
    fonts:
      selfhosted: true
      type:
        default: sans
      family:
        sans: Concourse
        serif: Valkyrie_B
        mono: DM Mono

  scripts:
    optional:
      mediumzoom: true

taxonomyMaxYears: 5
recentMaxYears: 5
outdatedAfterYears: 5
ephemeralSections:
  - technology

numberOfRecentArticles: 3
numberOfFeaturedArticles: 3
numberOfRelatedArticles: 5
iconsDir: /

# themeColorLit: hsl(42, 80%, 97%)
# themeColorBackgroundLit: hsl(207, 20%, 97%)
# themeNeutralBackgroundLit: hsl(207, 20%, 97%)

# themeColorDim: hsl(207, 80%, 25%)
# themeColorBackgroundDim: hsl(207, 20%, 25%)
# themeNeutralBackgroundDim: hsl(207, 20%, 25%)

sidebarTaxonomies: [tags]
navListCurrentSectionForTypes:
  - vitae
navListCurrentSectionInSection:
  - confidential
  - application
assetDownloadFolders:
  - downloads
home:
  section: _index
footer:
  section: _footer
  recentarticles: 3
  social:
    - linkedin
    - twitter
    - github
hidden:
  sections:
    - _error
    - _index
    - _footer
  pathelements:
    - confidential
    - private
    - hidden
website:
  name: simon.heimlicher.com
  tagline: Leadership & organizational transformation
  # NOTE: The description of the home page is taken from the home page's params
  description: |
    Simon Heimlicher: a passionate leader who writes about leadership, agile transformation and technology.
  established: 1999
  profile:
    headline: About Simon Heimlicher
    text: "Passionate leader with a track record of leading change: from agile transformation to strategy execution at a global scale"
    link: Simon Heimlicher
    url: about
image:
  thumbnail:
    - images/simon_heimlicher_16x9
    - images/simon_heimlicher_1x1
robots:
  index: true
  indeximages: true
  follow: true
social:
  twitter:
    id: simonheimlicher
  github:
    id: simonheimlicher
  linkedin:
    id: simonheimlicher
  stackoverflow:
    id: 617559/simon-heimlicher
  superuser:
    id: 69517/simon-heimlicher
  crossvalidated:
    id: 4467/simon-heimlicher
