canonicalBaseURL: https://simon.heimlicher.com/

siteAuthor: Simon Heimlicher
authors:
  simon-heimlicher:
    last_name: Heimlicher
    first_name: Simon
    email: AUTHOR_EMAIL
    name: Simon Heimlicher

showShare: false
mainSections:
  - articles
  - leadership
  - transformation
  - digitization
  - research
  - technology
# logo: images/simon_heimlicher_logo

responsive:
  breakpoints:
    width:
      # From this width upward, the mobile menu is hidden
      # and the full menu bar is shown
      mobileMenu: 60rem
      # From this width upward, font size is set to regular size
      narrow: 32rem

assets:
  styles:
    fonts:
      selfhosted: true
      type:
        default: sans
      family:
        sans: Concourse
        serif: Valkyrie_B
        mono: DM Mono

  scripts:
    mediumzoom: true
    posthog:
      key: phc_uCbhFRCieH9tPYbmlaLPtW6pZaEgnOfGENNgcC1KdlA
      # host: https://eu.posthog.com
      host: https://localization.heimlicher.com
      site: heimlicher.com


taxonomyMaxYears: 5
recentMaxYears: 5
outdatedAfterYears: 5
ephemeralSections:
  - technology

numberOfRecentArticles: 3
numberOfFeaturedArticles: 3
numberOfRelatedArticles: 5
iconsDir: /

# themeColorLit: hsl(42, 80%, 97%)
# themeColorBackgroundLit: hsl(207, 20%, 97%)
# themeNeutralBackgroundLit: hsl(207, 20%, 97%)

# themeColorDim: hsl(207, 80%, 25%)
# themeColorBackgroundDim: hsl(207, 20%, 25%)
# themeNeutralBackgroundDim: hsl(207, 20%, 25%)

sidebarTaxonomies: [tags]
navListCurrentSectionForTypes:
  - vitae
navListCurrentSectionInSection:
  - confidential
  - application
assetDownloadFolders:
  - downloads
home:
  section: _home
footer:
  section: _footer
  recentarticles: 3
  social:
    - linkedin
    - twitter
    - github
hidden:
  sections:
    - _error
    - _home
    - _footer
  pathelements:
    - confidential
    - private
    - hidden
website:
  name: simon.heimlicher.com
  tagline: Leadership & organizational transformation
  # NOTE: The description of the home page is taken from the home page's params
  description: |
    Simon Heimlicher: a passionate leader who writes about leadership, agile transformation and technology.
  established: 1999
  profile:
    headline: About Simon Heimlicher
    text: 'Passionate leader with a track record of leading change: from agile transformation to strategy execution at a global scale'
    link: Simon Heimlicher
    url: about
image:
  thumbnail:
    - images/simon_heimlicher_16x9
    - images/simon_heimlicher_1x1
robots:
  index: true
  indeximages: true
  follow: true
social:
  twitter:
    id: simonheimlicher
  github:
    id: simonheimlicher
  linkedin:
    id: simonheimlicher
  stackoverflow:
    id: 617559/simon-heimlicher
  superuser:
    id: 69517/simon-heimlicher
  crossvalidated:
    id: 4467/simon-heimlicher
