#!/usr/bin/env sh

# Build script for Vercel - combines dependency installation AND build
# Based on https://gohugo.io/host-and-deploy/host-on-vercel/
#
# IMPORTANT: Go and other tools must be installed in the SAME script that runs
# hugo, because Vercel runs install and build commands in separate shells.
# The PATH modifications don't persist between phases.

set -euo pipefail

# Version defaults (can be overridden via environment variables)
# HUGO_VERSION is set in Vercel environment (default: 0.153.5)
DART_SASS_VERSION="${DART_SASS_VERSION:-1.97.1}"
GO_VERSION="${GO_VERSION:-1.25.5}"

# Determine bin directory - use first writable PATH entry or create local bin
BIN_DIR="${BIN_DIR:-$PWD/bin}"
FIRST_PATH_DIR=$(echo $PATH | cut -d':' -f1)
if [ -w "$FIRST_PATH_DIR" ]; then
  BIN_DIR=$FIRST_PATH_DIR
  echo "Using first directory in PATH as BIN_DIR='$BIN_DIR'"
else
  echo "First directory in PATH '$FIRST_PATH_DIR' is not writable. Using BIN_DIR='$BIN_DIR'"
  mkdir -p "$BIN_DIR"
  export PATH="$BIN_DIR:$PATH"
fi

# Install Dart Sass
echo "Installing Dart Sass ${DART_SASS_VERSION} to BIN_DIR=${BIN_DIR}..."

# Download and extract Dart Sass directly into $BIN_DIR
curl -LJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
tar -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" -C "$BIN_DIR" --strip-components=1
rm -f "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"

# Check if Dart Sass is found
echo "Checking Dart Sass version..."
sass --embedded --version

# Check if Hugo finds the Dart Sass executable
echo "Checking Hugo environment..."
hugo env

# Install Go (required for Hugo modules)
echo "Installing Go ${GO_VERSION}..."
curl -sL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar -xz -C "${HOME}"
export PATH="${HOME}/go/bin:${PATH}"

# Check if go is found
echo "Checking Go version..."
go version

# Check Hugo environment
echo "Checking Hugo environment..."
hugo env

# Install NPM modules (from package.json generated by hugo mod npm pack)
echo "Installing Node modules..."
npm ci

# Install Hugo modules
echo "Installing Hugo modules..."
hugo mod get

# Create hugo_stats.json if missing (required for CSS purging)
if ! [ -f hugo_stats.json ]; then
  echo "Running hugo to create 'hugo_stats.json' as this required file is missing."
  hugo --gc --minify

  if ! [ -f hugo_stats.json ]; then
    echo "Fatal error: Hugo failed to create hugo_stats.json"
    exit 1
  fi
fi

# Run the actual build
echo "Running production build..."
ENVIRONMENT="${VERCEL_ENV:-production}"
if [ "$ENVIRONMENT" = "production" ]; then
  HUGO_ENV="prod"
elif [ "$ENVIRONMENT" = "preview" ]; then
  HUGO_ENV="stage"
else
  HUGO_ENV="devel"
fi

echo "Building with environment: $HUGO_ENV"
hugo --gc --minify --environment="$HUGO_ENV"

echo "Build complete!"
