#!/usr/bin/env sh

# Build script for Vercel - combines dependency installation AND build
# Based on https://gohugo.io/host-and-deploy/host-on-vercel/
#
# IMPORTANT: Go and other tools must be installed in the SAME script that runs
# hugo, because Vercel runs install and build commands in separate shells.
# The PATH modifications don't persist between phases.

set -euo pipefail

# Version defaults (can be overridden via environment variables)
# HUGO_VERSION is set in Vercel environment (default: 0.153.5)
DART_SASS_VERSION="${DART_SASS_VERSION:-1.97.1}"
GO_VERSION="${GO_VERSION:-1.25.5}"

# Install all dependencies to ${HOME}/.local following Hugo's official approach
LOCAL_DIR="${HOME}/.local"
mkdir -p "${LOCAL_DIR}"

# Install Dart Sass (following Hugo's official Vercel guide)
echo "Installing Dart Sass ${DART_SASS_VERSION}..."
curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
tar -C "${LOCAL_DIR}" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
rm -f "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
export PATH="${LOCAL_DIR}/dart-sass:${PATH}"

# Verify Dart Sass installation
echo "Verifying Dart Sass installation..."
ls -la "${LOCAL_DIR}/dart-sass/"
echo "PATH=${PATH}"

# Check if Dart Sass is found
echo "Checking Dart Sass version..."
sass --embedded --version

# Check if Hugo finds the Dart Sass executable
echo "Checking Hugo environment..."
hugo env

# Install Go (required for Hugo modules)
echo "Installing Go ${GO_VERSION}..."
curl -sL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar -C "${LOCAL_DIR}" -xzf -
export PATH="${LOCAL_DIR}/go/bin:${PATH}"

# Check if go is found
echo "Checking Go version..."
go version

# Check Hugo environment
echo "Checking Hugo environment..."
hugo env

# Install NPM modules (from package.json generated by hugo mod npm pack)
echo "Installing Node modules..."
npm ci

# Install Hugo modules
echo "Installing Hugo modules..."
hugo mod get

# Create hugo_stats.json if missing (required for CSS purging)
if ! [ -f hugo_stats.json ]; then
  echo "Running hugo to create 'hugo_stats.json' as this required file is missing."
  hugo --gc --minify

  if ! [ -f hugo_stats.json ]; then
    echo "Fatal error: Hugo failed to create hugo_stats.json"
    exit 1
  fi
fi

# Run the actual build
echo "Running production build..."
ENVIRONMENT="${VERCEL_ENV:-production}"
if [ "$ENVIRONMENT" = "production" ]; then
  HUGO_ENV="prod"
elif [ "$ENVIRONMENT" = "preview" ]; then
  HUGO_ENV="stage"
else
  HUGO_ENV="devel"
fi

echo "Building with environment: $HUGO_ENV"
hugo --gc --minify --environment="$HUGO_ENV"

echo "Build complete!"
