#!/usr/bin/env sh

# Build script for Vercel
# Based on https://www.brycewray.com/posts/2022/03/using-dart-sass-hugo-sequel/
# which is based on https://discourse.gohugo.io/t/using-dart-sass-hugo-and-netlify/37099/7

set -euo pipefail

# Version defaults (can be overridden via environment variables)
# HUGO_VERSION is set in Vercel environment (default: 0.153.5)
DART_SASS_VERSION="${DART_SASS_VERSION:-1.97.1}"
GO_VERSION="${GO_VERSION:-1.25.5}"

BIN_DIR="${BIN_DIR:-$PWD/bin}"
FIRST_PATH_DIR=$(echo $PATH | cut -d':' -f1)
if [ -w "$FIRST_PATH_DIR" ]; then
  BIN_DIR=$FIRST_PATH_DIR
  echo "Using first directory in PATH as BIN_DIR='$BIN_DIR'"
else
  echo "First directory in PATH '$FIRST_PATH_DIR' is not writable. Using BIN_DIR='$BIN_DIR'"
  mkdir -p "$BIN_DIR"
fi


echo "Installing Dart Sass ${DART_SASS_VERSION} to BIN_DIR=${BIN_DIR}..."

# Download and extract Dart Sass directly into $BIN_DIR
curl -LJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
tar -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" -C "$BIN_DIR" --strip-components=1
rm -f "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"

# Check if Dart Sass is found
echo "Checking Dart Sass version..."
sass --embedded --version

# Check if Hugo finds the Dart Sass executable
echo "Checking Hugo environment..."
hugo env

# Install Go to allow Hugo modules to be installed
echo "Installing Go ${GO_VERSION}..."
curl -sL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar -xz -C "${HOME}"
export PATH="${HOME}/go/bin:${PATH}"

# Check if go is found
echo "Checking Go version..."
go version

# Install NPM modules (from package.json generated by hugo mod npm pack)
echo "Installing Node modules..."
npm ci

# Install Hugo modules
echo "Installing Hugo modules..."
hugo mod get

if ! [ -f hugo_stats.json ]; then
  echo "Running hugo to create 'hugo_stats.json' as this required file is missing."
  hugo --gc --minify

  if ! [ -f hugo_stats.json ]; then
    echo "Fatal error: Hugo failed to create hugo_stats.json"
    exit 1
  fi
fi
